# -*- coding: utf-8 -*-
"""Copia de Mi primer programa1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q1DqDllLJ8n3I6UTj-k1fPGPX0hkg4fx

##Mi primer Programa

variables  y cadenas
"""

saludo1 = "bienvenida"
saludo2= "te ves muy hermosa"
saludo = saludo1 + "," + saludo2

print(saludo)

"""Tuplas 

"""

registro = ("omar", "montoya", (20,9,2002))
nombre, apellido, nacimiento = registro

print(nombre)
print(apellido)

año = nacimiento[2]
mes = nacimiento [1]
dia = nacimiento [0]

print(año)
print(mes)
print(dia)

"""Listas"""

b = ["carro","moto","bicicleta","avion"]
print(b)

b.append ("monopatin")
print(b)

b.insert(0, "rueda")
print(b)

print(len(b))

b[3:5] = ["camion", "patineta"]
print(b)

"""copia de listas

"""

a = [1, 2, 3, 4, 5]

b = a

b[4] = 0

print (a)

a = [1,2, 4, 5]
c = a[:]

c[1] = 3

print(a)
print(c)

"""Matrices"""

a = [[1, 2, 3, 4], \
     [5, 6, 7, 8], \
     [9, 10, 11, 12]]

print(a)

print(a[0])
print(a[1])
print(a[2])

print(a[2][2])

"""operadores aritmeticos"""

s = "bienvenida "
t = "guapa"
c = [2, 3, 4, 5]

print(s * 3)

print(c + [6, 7])

"""PRACTICA"""

LOTERIA = ("omar", "33", (2, 5 , 6))
ganador, numeroganador, numeros = LOTERIA

print(ganador)
print(numeroganador)

primero = numeros[0]
segundo = numeros[1]
tercero = numeros[2]

print(primero)
print(segundo)
print(tercero)

numeros = [34, 2, 33, 24, 5]

numeros.reverse()
print(numeros)

numeros.sort(reverse= True)
print(numeros)

numeros = len(numeros)

print("longitud de la lista es de: ")
print(numeros)